### ISSUE TITLE
Chevereto API

### ISSUE THREAD

**Issue by rodber** [Largehawiian/ImgBBAPI#1]
Hey @Largehawiian 

Fyi ImgBB is based on Chevereto. Why limit your project to one service if it could be used by thousands running Chevereto-based systems?

Check the API docs: https://v4-docs.chevereto.com/developer/api/api-v1.html

Cheers!

**Comment by Largehawiian** [comment]
I'd be happy to extend the functionality or fork this project to a more generalized module. Would you be open to collaborating ?
